---
# easy RHEL 6.x tomcat playbook as an example.
# this is a test for ec2 user-data  
# local.yml is used for pull-based Ansible setup.

- hosts: localhost
  vars:
  # Here are variables related to the Tomcat installation
    http_port: 8080
    https_port: 8443
  # This will configure a default manager-gui user:
    admin_username: admin
    admin_password: adminsecret 
  user: root

  roles:
    - tomcat-standalone/roles/selinux
    - tomcat-standalone/roles/tomcat